{"sections":[],"identifier":{"url":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/activateOnceError","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"Adapty"}],"symbolKind":"case","externalID":"s:6Adapty0A5ErrorV0B4CodeO012activateOnceB0yA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activateOnceError"}],"roleHeading":"Case","title":"AdaptyError.ErrorCode.activateOnceError","role":"symbol"},"abstract":[{"type":"text","text":"It is not possible to call "},{"code":".activate","type":"codeVoice"},{"type":"text","text":" method more than once."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activateOnceError","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/activateonceerror"]}],"hierarchy":{"paths":[["doc:\/\/ios-sdk.Adapty\/documentation\/Adapty","doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"references":{"doc://ios-sdk.Adapty/documentation/Adapty":{"title":"Adapty","role":"collection","url":"\/documentation\/adapty","type":"topic","kind":"symbol","identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty","abstract":[]},"doc://ios-sdk.Adapty/documentation/Adapty/AdaptyError":{"url":"\/documentation\/adapty\/adaptyerror","type":"topic","kind":"symbol","role":"symbol","title":"AdaptyError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdaptyError"}],"identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"abstract":[]},"doc://ios-sdk.Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"type":"topic","title":"AdaptyError.ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}]},"doc://ios-sdk.Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/activateOnceError":{"identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/activateOnceError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"activateOnceError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/activateonceerror","type":"topic","abstract":[{"type":"text","text":"It is not possible to call "},{"code":".activate","type":"codeVoice"},{"type":"text","text":" method more than once."}],"title":"AdaptyError.ErrorCode.activateOnceError","role":"symbol"}}}