{"hierarchy":{"paths":[["doc:\/\/Adapty\/documentation\/Adapty","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cloudServiceRevoked","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"User has revoked permission to use this cloud service."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceRevoked"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicerevoked"]}],"metadata":{"roleHeading":"Case","title":"AdaptyError.ErrorCode.cloudServiceRevoked","symbolKind":"case","externalID":"s:6Adapty0A5ErrorV0B4CodeO19cloudServiceRevokedyA2EmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceRevoked"}],"modules":[{"name":"Adapty"}],"role":"symbol"},"references":{"doc://Adapty/documentation/Adapty/AdaptyError":{"title":"AdaptyError","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","url":"\/documentation\/adapty\/adaptyerror","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdaptyError"}],"abstract":[]},"doc://Adapty/documentation/Adapty":{"identifier":"doc:\/\/Adapty\/documentation\/Adapty","url":"\/documentation\/adapty","type":"topic","title":"Adapty","kind":"symbol","role":"collection","abstract":[]},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"title":"AdaptyError.ErrorCode","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"abstract":[]},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/cloudServiceRevoked":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceRevoked"}],"title":"AdaptyError.ErrorCode.cloudServiceRevoked","type":"topic","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicerevoked","role":"symbol","abstract":[{"type":"text","text":"User has revoked permission to use this cloud service."}],"identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceRevoked","kind":"symbol"}}}