{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceRevoked"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicerevoked"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceRevoked","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User has revoked permission to use this cloud service."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceRevoked"}],"title":"AdaptyError.ErrorCode.cloudServiceRevoked","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6Adapty0A5ErrorV0B4CodeO19cloudServiceRevokedyA2EmF","modules":[{"name":"Adapty"}]},"hierarchy":{"paths":[["doc:\/\/Adapty\/documentation\/Adapty","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"references":{"doc://Adapty/documentation/Adapty":{"role":"collection","title":"Adapty","abstract":[],"identifier":"doc:\/\/Adapty\/documentation\/Adapty","kind":"symbol","type":"topic","url":"\/documentation\/adapty"},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"role":"symbol","title":"AdaptyError.ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum"},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/cloudServiceRevoked":{"role":"symbol","title":"AdaptyError.ErrorCode.cloudServiceRevoked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceRevoked"}],"abstract":[{"type":"text","text":"User has revoked permission to use this cloud service."}],"identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceRevoked","kind":"symbol","type":"topic","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicerevoked"},"doc://Adapty/documentation/Adapty/AdaptyError":{"role":"symbol","title":"AdaptyError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdaptyError"}],"abstract":[],"identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"url":"\/documentation\/adapty\/adaptyerror"}}}