{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicenetworkconnectionfailed"]}],"metadata":{"modules":[{"name":"Adapty"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudServiceNetworkConnectionFailed","kind":"identifier"}],"title":"AdaptyError.ErrorCode.cloudServiceNetworkConnectionFailed","roleHeading":"Case","externalID":"s:6Adapty0A5ErrorV0B4CodeO35cloudServiceNetworkConnectionFailedyA2EmF","symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/Adapty\/documentation\/Adapty","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"abstract":[{"type":"text","text":"The device could not connect to the network."}],"identifier":{"url":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceNetworkConnectionFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceNetworkConnectionFailed"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://Adapty/documentation/Adapty":{"identifier":"doc:\/\/Adapty\/documentation\/Adapty","url":"\/documentation\/adapty","type":"topic","title":"Adapty","kind":"symbol","role":"collection","abstract":[]},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/cloudServiceNetworkConnectionFailed":{"role":"symbol","title":"AdaptyError.ErrorCode.cloudServiceNetworkConnectionFailed","abstract":[{"text":"The device could not connect to the network.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicenetworkconnectionfailed","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceNetworkConnectionFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudServiceNetworkConnectionFailed","kind":"identifier"}]},"doc://Adapty/documentation/Adapty/AdaptyError":{"title":"AdaptyError","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","url":"\/documentation\/adapty\/adaptyerror","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdaptyError"}],"abstract":[]},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"title":"AdaptyError.ErrorCode","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"abstract":[]}}}